### ISSUE TITLE
calendarize_pages with TYPO3 v12: Not possible to add events in edit form "pages" (unless doktype is 132)

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize_pages#12]
When editing a pages record in the BE, in v11 it was possible to add calendarize events (even if the doktype was not doktype= 132).

In v12, this does not seem to be possible.

In v11, the fields are displayed in the last tab "Deepl Translate"

My assumption is that in v12 it is necessary to select doktype=132, otherwise it is not possible to add events to pages with calendarize_pages. Is that correct?

## Versions

* TYPO3: 12.4.16
* calendarize: 13.0.7
* calendarize_pages: 4.0.0
* PHP 8.2

**Comment by lochmueller** [comment]
You are right. The default is the 132 doktype. But ... `In v12, this does not seem to be possible.` -> You can add the calendarize fields to every type of the pages table in your custom extension. I think this change is enough to fit your requirement (all the other views/plugins should handle the pages right, even it is not 132 doktype).

Regards,
Tim
