### ISSUE TITLE
[Task] Add page.description to page object

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize_pages#2]
I would love to have the page.description field available for use in fluid template as equivalent to event abstract.

**Comment by lochmueller** [comment]
Hey @artus70 
Nice idea. Feel free to add this property to the Page model.
Regards,
Tim

**Comment by artus70** [comment]
Unfortunately, I'm not a developer. I won't be able to update the Page model. I just can manage to integrate existing properties in the fluid template.

**Comment by lochmueller** [comment]
V1.0.1 hat nun weitere properties:
https://github.com/lochmueller/calendarize_pages/blob/main/Classes/Domain/Model/Page.php

Regards,
Tim

**Comment by artus70** [comment]
Cool, thx!
