### ISSUE TITLE
Feature: Add {page.categories} object to fluid template

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize_pages#3]
At the moment I can't output system categories assigned to a web page in the fluid template. `{page.categories}` does not exist - can this be added so that the categories can be output in the frontend?

(Tested unsuccessfully with `<f:debug>{page}</debug>`.)

**Comment by lochmueller** [comment]
Only the properties that are mapped in the model are accessable: https://github.com/lochmueller/calendarize_pages/blob/main/Classes/Domain/Model/Page.php Feel free to send a pull request adding the categories to the model.

**Comment by lochmueller** [comment]
![Bildschirmfoto 2021-04-21 um 22 04 03](https://user-images.githubusercontent.com/3907126/115614113-88bd7a80-a2ed-11eb-97ec-7190f1ccab68.png)

I tested it in the current version and it works well. Could you check this again? Please add some more information about versions of TYPO3, calendarize, calendarize_pages? Do you use another field than "categories" in pages for categories?

Regards,
Tim

**Comment by artus70** [comment]
Hopefully I'll have a suitable testing environment soon ...

**Comment by artus70** [comment]
I just checked - my pull request https://github.com/lochmueller/calendarize_pages/pull/4 had already solved the problem. I close the issue.
