### ISSUE TITLE
showing calendarized pages in list view depending on page category does not work

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize_pages#6]
Showing and linking pages in calendarize list view works great, but only if the calendarize plugin has no categories assigned! When filtering by using categories, the categories of the calendarized pages (which actually match the plugin category setting) are not recognized, so no pages are listed then.

Does calendarize_pages need some additional search functionality to make that work? (Unfortunately, I don't know enough about plug-in programming to do this myself.)

**Comment by artus70** [comment]
Can anyone help here? For the practical use of calendarize_pages it is very important that categories are taken into account when selecting pages to display in list view. Thanks.

**Comment by lochmueller** [comment]
Hey @artus70 
you are right. The slot for the search is missing in the calendarize_pages extension. I will check this in the next days/weeks.
Regards,
Tim
