### ISSUE TITLE
Remove calendarized Pages from add buttons in module view

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize_pages#8]
It does not make much sense that buttons for calendarized pages are also offered in web->Calendarize. Clicking on them creates a subordinate web page that otherwise has nothing to do with the page clicked on.

Moreover, the list of blue buttons is insanely growing with every new calendarized page being created.

I suggest removing "CalendarizePages" here completely.

![grafik](https://user-images.githubusercontent.com/367315/125814126-a7bf5cf8-15a9-475d-bef3-a1eef223000f.png)

**Comment by lochmueller** [comment]
Good point. I will check how to handle this case...

**Comment by lochmueller** [comment]
Hey @artus70 
I close this issue. With the next EXT:calendarize release you can select a "type" in the filter (is stored in the user settings, so you have to select it once). After the selection you will only see the "create new" buttons for the specific event type. I think this is a good solution for this problem without add some more "configuration options" in the "calendarize registration process".

Commit: https://github.com/lochmueller/calendarize/commit/c741fcfd2b50174c4eb6096d295af3f371bb8667
More information (Screenshot of the selection): https://github.com/lochmueller/calendarize/issues/538

Regards,
Tim
